### ISSUE TITLE
[Figma] 작업완료

### ISSUE THREAD

**Issue by haizellatte** [haizellatte/This-and-That#1]
## Todo
웹 포트폴리오 피그마 작업 완료

## Description
1. [ ] 메인 상단, 스킬, 다른 경험, 교육 Section
2. [ ] 🔥 프로젝트 Section

## Progress
1. [ ] 개인회고 블로깅 -> 아이콘으로 링크 걸기
2. [ ] 내가 구현한 페이지에서 자랑하고픈 코드 소개 (직접 코드 블록 넣어도 OK)
3. [ ] 에러 코드 / 우탕탕탕 & 어려움 극복 사례

## Time Required
1 Day
