### ISSUE TITLE
[TypeScript & React] 웹 포트폴리오 기능 구현

### ISSUE THREAD

**Issue by haizellatte** [haizellatte/This-and-That#15]
## Progress
1. [ ] 
2. [ ]
3. [ ]

## Todo
1. [ ] 헤더 position : sticky
2. [ ] 스크롤 프로그레스 바
3. [ ] 드래그 시 색깔 지정
4. [ ] 맨 위로 이동하는 버튼
5. [ ] 복사 금지 기능
6. [ ] 이미지로 저장하기(PDF) 기능
7. [ ] 이력서 사이트로 이동하기 기능

## Time Required
3 days
